package zone.clanker.gradle.srcx.analysis

import zone.clanker.gradle.srcx.model.ImportantSymbol
import zone.clanker.gradle.srcx.model.ImportantSymbolReason
import zone.clanker.gradle.srcx.model.ImportantSymbolSignals
import zone.clanker.gradle.srcx.model.SymbolDetailKind
import zone.clanker.gradle.srcx.model.WorkspaceIndex
import zone.clanker.gradle.srcx.model.WorkspaceRelationshipKind
import zone.clanker.gradle.srcx.model.WorkspaceSymbolUsage

/** Pure, centralized policy for selecting a bounded set of important workspace declarations. */
object ImportantSymbolPolicy {
    /** Default maximum number of symbol documents generated by a caller. */
    const val DEFAULT_MAX_DOCUMENTS = 100

    const val HIGH_WORKSPACE_INBOUND_THRESHOLD = 5
    const val HIGH_WORKSPACE_OUTBOUND_THRESHOLD = 5
    const val MULTIPLE_IMPLEMENTATIONS_THRESHOLD = 2
    const val UNUSUAL_CONNECTIVITY_THRESHOLD = 8

    // This exceeds every non-cross-build score combined, preserving cross-build APIs under the default ranking.
    val CROSS_BUILD_INBOUND_SCORE = ImportantSymbolReason.CROSS_BUILD_INBOUND.score
    val HIGH_WORKSPACE_INBOUND_SCORE = ImportantSymbolReason.HIGH_WORKSPACE_INBOUND.score
    val MULTIPLE_IMPLEMENTATIONS_SCORE = ImportantSymbolReason.MULTIPLE_IMPLEMENTATIONS.score
    val ENTRY_POINT_SCORE = ImportantSymbolReason.ENTRY_POINT.score
    val DEPENDENCY_CYCLE_SCORE = ImportantSymbolReason.DEPENDENCY_CYCLE.score
    val HIGH_WORKSPACE_OUTBOUND_SCORE = ImportantSymbolReason.HIGH_WORKSPACE_OUTBOUND.score
    val UNUSUAL_CONNECTIVITY_SCORE = ImportantSymbolReason.UNUSUAL_CONNECTIVITY.score
    val ANTI_PATTERN_INVOLVEMENT_SCORE = ImportantSymbolReason.ANTI_PATTERN_INVOLVEMENT.score

    /**
     * Select important symbols in score-descending, scoped-identity order.
     *
     * Test source sets are excluded unless explicitly requested.
     * [signals] are matched by exact workspace identity only.
     */
    fun select(
        index: WorkspaceIndex,
        signals: ImportantSymbolSignals = ImportantSymbolSignals(),
        maxDocuments: Int = DEFAULT_MAX_DOCUMENTS,
        includeTestSourceSets: Boolean = false,
    ): List<ImportantSymbol> {
        require(maxDocuments >= 0) { "maxDocuments must be >= 0" }

        return index.usages
            .asSequence()
            .filter { includeTestSourceSets || !isTestSourceSet(it.symbol.sourceSet) }
            .map { it.withoutImports() }
            .mapNotNull { candidate(it, signals) }
            .sortedWith(compareByDescending<ImportantSymbol> { it.score }.thenBy { it.symbol.identity.value })
            .take(maxDocuments)
            .toList()
    }

    private fun candidate(
        usage: WorkspaceSymbolUsage,
        signals: ImportantSymbolSignals,
    ): ImportantSymbol? {
        val reasons = reasonsFor(usage, signals)
        return reasons.takeIf { it.isNotEmpty() }?.let {
            ImportantSymbol(
                symbol = usage.symbol,
                reasons = reasons,
                score = reasons.sumOf(::scoreFor),
                usage = usage,
            )
        }
    }

    private fun reasonsFor(
        usage: WorkspaceSymbolUsage,
        signals: ImportantSymbolSignals,
    ): List<ImportantSymbolReason> {
        val identity = usage.symbol.identity
        val implementationCount = usage.incoming.count { it.kind == WorkspaceRelationshipKind.IMPLEMENTS }
        val connectivity = usage.incoming.size + usage.outgoing.size
        return listOfNotNull(
            ImportantSymbolReason.CROSS_BUILD_INBOUND.takeIf { usage.crossBuildInbound > 0 },
            ImportantSymbolReason.HIGH_WORKSPACE_INBOUND.takeIf {
                usage.workspaceInbound >= HIGH_WORKSPACE_INBOUND_THRESHOLD
            },
            ImportantSymbolReason.MULTIPLE_IMPLEMENTATIONS.takeIf {
                usage.symbol.kind == SymbolDetailKind.INTERFACE &&
                    implementationCount >= MULTIPLE_IMPLEMENTATIONS_THRESHOLD
            },
            ImportantSymbolReason.ENTRY_POINT.takeIf { identity in signals.entryPoints },
            ImportantSymbolReason.DEPENDENCY_CYCLE.takeIf { identity in signals.cycleParticipants },
            ImportantSymbolReason.HIGH_WORKSPACE_OUTBOUND.takeIf {
                usage.outgoing.size >= HIGH_WORKSPACE_OUTBOUND_THRESHOLD
            },
            ImportantSymbolReason.UNUSUAL_CONNECTIVITY.takeIf {
                connectivity >= UNUSUAL_CONNECTIVITY_THRESHOLD
            },
            ImportantSymbolReason.ANTI_PATTERN_INVOLVEMENT.takeIf { identity in signals.antiPatternSymbols },
        )
    }

    private fun scoreFor(reason: ImportantSymbolReason): Int = reason.score

    private fun WorkspaceSymbolUsage.withoutImports(): WorkspaceSymbolUsage =
        copy(
            incoming = incoming.filterNot { it.kind == WorkspaceRelationshipKind.IMPORT },
            outgoing = outgoing.filterNot { it.kind == WorkspaceRelationshipKind.IMPORT },
        )

    private fun isTestSourceSet(sourceSet: String): Boolean =
        sourceSet == "test" || sourceSet.startsWith("test") || sourceSet.endsWith("Test")
}
